### ISSUE TITLE
Tracking issue for all commands handlers support

### ISSUE THREAD

**Issue by Drevoed** [AttorneyOnline-Unofficial/rusttorney#18]
In order to have a fully working implementation of AO 2.8 protocol we need to write handlers for all types of commands that can come from client. ***And*** we need to fully support all the commands that the server can send in response.

**Client commands handlers track list:**
- [x] Handshake (HI)
- [ ] ClientVersion (ID)
- [x] KeepAlive (CH)
- [ ] AskListLengths (ashkchaa)
- [ ] AskListCharacters (askchar)
- [ ] CharacterList (AN) // Deprecated? (AO1)
- [ ] EvidenceList (AE) // Deprecated? (AO1)
- [ ] MusicList (AM) // Deprecated? (AO1)
- [ ] AO2CharacterList (RC)
- [ ] AO2MusicList (RM)
- [ ] AO2Ready (RD)
- [ ] SelectCharacter (CC)
- [ ] ICMessage (MS)
- [ ] OOCMessage (CT)
- [ ] PlaySong (MC)
- [ ] WTCEButtons (RT)
- [ ] SetCasePreferences (SETCASE)
- [ ] CaseAnnounce (CASEA)
- [ ] Penalties (HP)
- [ ] AddEvidence (PE)
- [ ] DeleteEvidence (DE)
- [ ] EditEvidence (EE)
- [ ] CallModButton (ZZ)

**Server commands track list:**
- [x] Handshake (HI)
- [x]  KeepAlive (CHECK)
- [x] Decryptor (decryptor)
- [x] BanReason (BD)
- [x] ServerVersion (ID)
- [x] PlayerCount (PN)
- [ ] Other commands // NYI
